import { useStore } from '@/lib/store/useStore';
import { ContrastTheme, FontFamilyPreference, LetterSpacing, LineHeight } from '@/types';

export interface WebMCPToolDefinition {
  name: string;
  description: string;
  inputSchema: Record<string, any>;
  annotations?: {
    readOnlyHint?: boolean;
    untrustedContentHint?: boolean;
  };
  execute: (input: any) => Promise<any>;
}

export function createCanonicalWebMCPTools(): WebMCPToolDefinition[] {
  return [
    // 1. ADJUST READING MODE & ERGONOMIC TYPOGRAPHY
    {
      name: 'adjust_reading_mode',
      description: 'Controls visual accessibility overlays, contrast themes, and spacing to eliminate visual stress and crowding for dyslexic readers.',
      inputSchema: {
        type: 'object',
        properties: {
          fontFamily: {
            type: 'string',
            enum: ['lexend', 'atkinson', 'opendyslexic', 'system'],
            description: 'Accessible typeface preference to aid character discrimination.'
          },
          bionicReading: {
            type: 'boolean',
            description: 'When true, highlights the initial letters of words to guide eye fixations.'
          },
          letterSpacing: {
            type: 'string',
            enum: ['normal', 'wide', 'extra-wide'],
            description: 'Character tracking to prevent visual crowding.'
          },
          lineHeight: {
            type: 'string',
            enum: ['normal', 'relaxed', 'loose'],
            description: 'Vertical line leading between lines of text.'
          },
          contrastTheme: {
            type: 'string',
            enum: ['soft-cream', 'warm-peach', 'calming-sage', 'muted-slate', 'yellow-on-black'],
            description: 'High-contrast or tinted background to eliminate photopic glare and halation.'
          },
          readingRuler: {
            type: 'boolean',
            description: 'Toggles a translucent horizontal reading guide bar under the cursor.'
          }
        }
      },
      // Deliberately OMIT readOnlyHint: Mutates visible UI
      execute: async (params: {
        fontFamily?: FontFamilyPreference;
        bionicReading?: boolean;
        letterSpacing?: LetterSpacing;
        lineHeight?: LineHeight;
        contrastTheme?: ContrastTheme;
        readingRuler?: boolean;
      }) => {
        const store = useStore.getState();
        store.setReadingPreferences(params);
        store.setDockOpen(false);
        store.showToast('✓ Reading mode configuration applied by NOD Agent');
        store.announce('Reading mode and typography adjusted.');
        store.setMascotMood('nodding');
        setTimeout(() => store.setMascotMood('idle'), 2000);
        return {
          success: true,
          message: 'Reading mode and typography updated live on canvas.',
          activePreferences: useStore.getState().readingPreferences,
        };
      }
    },

    // 2A. GET ACTIVE ARTICLE (Read into Agent LLM Context)
    {
      name: 'get_active_article',
      description: 'Reads the active article markdown content, title, and readability score directly into the agent context for cognitive analysis or simplification.',
      inputSchema: {
        type: 'object',
        properties: {}
      },
      annotations: {
        readOnlyHint: true,
        untrustedContentHint: true, // Community content protection
      },
      execute: async () => {
        const store = useStore.getState();
        const article = store.activeArticle;
        if (!article) {
          throw new Error('No article is currently open. Please navigate to or peek at an article first.');
        }
        return {
          id: article.id,
          title: article.title,
          content: article.content.rawMarkdown,
          category: article.category,
          clarityScore: article.metrics.clarityScore,
          clarityGrade: article.metrics.clarityGrade,
          wordCount: article.metrics.wordCount,
          sentenceCount: article.metrics.sentenceCount,
        };
      }
    },

    // 2B. RENDER SIMPLIFIED VIEW (Live DOM Mutation)
    {
      name: 'render_simplified_view',
      description: 'Renders the agent-simplified plain-English text and key takeaways directly onto the active reading canvas. Activates the in-place non-destructive toggle.',
      inputSchema: {
        type: 'object',
        properties: {
          simplifiedContent: {
            type: 'string',
            description: 'The plain-language, short-sentence simplified version of the article generated by the agent.'
          },
          keyTakeaways: {
            type: 'array',
            items: { type: 'string' },
            description: '3 to 5 high-level bulleted summary points for working memory support.'
          }
        },
        required: ['simplifiedContent']
      },
      // Deliberately OMIT readOnlyHint: Mutates visible UI
      execute: async ({ simplifiedContent, keyTakeaways = [] }: { simplifiedContent: string; keyTakeaways?: string[] }) => {
        if (!simplifiedContent || simplifiedContent.trim().length < 10) {
          throw new Error('Simplified content must contain at least 10 characters.');
        }
        const store = useStore.getState();
        store.setSimplifiedView({
          simplifiedContent,
          keyTakeaways,
          isActive: true,
        });
        store.showToast('✓ Plain-language view rendered by NOD Agent');
        store.announce('Article has been simplified into plain English.');
        store.setMascotMood('nodding');
        setTimeout(() => store.setMascotMood('idle'), 2500);
        return {
          success: true,
          message: 'Simplified view rendered live on canvas with comparison switch.',
        };
      }
    },

    // 3. ASSIST DRAFT CONTENT (8-12 WPM Telegraphic Shorthand Expander)
    {
      name: 'assist_draft_content',
      description: 'Assists the author in expanding raw telegraphic shorthand or phonetic text into clear sentences while strictly preserving their authentic voice. Directly opens the Binary Gatekeeper Review Modal on the screen.',
      inputSchema: {
        type: 'object',
        properties: {
          rawText: {
            type: 'string',
            description: 'The unpolished, phonetic, or shorthand thoughts provided by the user. If omitted, uses the current text in the editor.'
          },
          intent: {
            type: 'string',
            enum: ['spelling_grammar_cleanup', 'shorten_and_clarify', 'expand_telegraphic_shorthand'],
            description: 'The specific editorial assistance desired.'
          }
        }
      },
      // Deliberately OMIT readOnlyHint: Mutates editor state & launches Binary Review Modal
      execute: async ({ rawText, intent = 'expand_telegraphic_shorthand' }: { rawText?: string; intent?: string }) => {
        const store = useStore.getState();
        const inputText = (rawText && rawText.trim().length > 0) ? rawText.trim() : store.editorDraft.content.trim();
        if (!inputText || inputText.length < 3) {
          throw new Error('Input text must be at least 3 characters. Provide rawText or type notes in the editor.');
        }

        // Lightweight client expansion logic to fulfill prototype requirements
        let expanded = inputText;
        if (intent === 'expand_telegraphic_shorthand') {
          expanded = inputText
            .split('\n')
            .map((line) => {
              const clean = line.replace(/^[-*•]\s*/, '').trim();
              if (!clean) return '';
              const capitalized = clean.charAt(0).toUpperCase() + clean.slice(1);
              return capitalized.endsWith('.') ? capitalized : `${capitalized}.`;
            })
            .filter(Boolean)
            .join(' ');
        }

        // Trigger binary gatekeeper review on the active canvas
        store.proposeEditorDraft({ proposedText: expanded });

        return {
          original: inputText,
          proposal: expanded,
          intent,
          wordCountOriginal: inputText.split(/\s+/).length,
          wordCountExpanded: expanded.split(/\s+/).length,
          message: 'Expansion generated and opened in the Binary Gatekeeper Review Modal on screen.',
        };
      }
    },

    // 4. SEARCH COMMUNITY FEED
    {
      name: 'search_community_feed',
      description: 'Searches published community articles, accessibility tips, and discussions.',
      inputSchema: {
        type: 'object',
        properties: {
          query: {
            type: 'string',
            description: 'Search keywords, e.g. "dyslexia", "spacing", "adhd".'
          },
          category: {
            type: 'string',
            enum: ['all', 'tips', 'stories', 'questions', 'resources', 'discussion'],
            description: 'Filter by topic tag.'
          }
        },
        required: ['query']
      },
      annotations: {
        readOnlyHint: true,
        untrustedContentHint: true, // Community content hint
      },
      execute: async ({ query, category = 'all' }: { query: string; category?: string }) => {
        if (!query || query.trim().length < 2) {
          throw new Error('Query must be at least 2 characters.');
        }
        const res = await fetch(`/api/feed?category=${encodeURIComponent(category)}`);
        const data = await res.json();
        const lowerQ = query.toLowerCase();
        
        const matched = (data.items || []).filter((item: any) =>
          item.title.toLowerCase().includes(lowerQ) ||
          item.summary.toLowerCase().includes(lowerQ) ||
          (item.tags && item.tags.some((t: string) => t.toLowerCase().includes(lowerQ)))
        );

        return {
          query,
          category,
          resultCount: matched.length,
          results: matched.slice(0, 5),
        };
      }
    },

    // 5. PUBLISH POST / ARTICLE
    {
      name: 'publish_article',
      description: 'Submits a new article or discussion post to the community feed with dual-store persistence.',
      inputSchema: {
        type: 'object',
        properties: {
          title: {
            type: 'string',
            description: 'Title of the article (under 120 characters).'
          },
          content: {
            type: 'string',
            description: 'Full markdown body text.'
          },
          category: {
            type: 'string',
            enum: ['tips', 'stories', 'questions', 'resources', 'discussion'],
            description: 'Category tag for the post.'
          },
          tags: {
            type: 'array',
            items: { type: 'string' },
            description: 'Topic tags.'
          }
        },
        required: ['title', 'content', 'category']
      },
      // Deliberately OMIT readOnlyHint: High-impact mutation requiring confirmation
      execute: async ({ title, content, category, tags = [] }: { title: string; content: string; category: string; tags?: string[] }) => {
        if (!title || title.trim().length < 3) throw new Error('Title must be at least 3 characters.');
        if (!content || content.trim().length < 10) throw new Error('Content must be at least 10 characters.');

        const res = await fetch('/api/articles', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            title,
            content,
            category,
            tags,
            author: { id: 'agent-user', name: 'Community Member' },
          }),
        });

        if (!res.ok) {
          throw new Error(`Failed to publish article: HTTP ${res.status}`);
        }

        const result = await res.json();
        const store = useStore.getState();
        store.announce(`Your article "${title}" has been published to the community feed.`);
        store.setMascotMood('nodding');
        setTimeout(() => store.setMascotMood('idle'), 3000);

        // Notify UI to refresh feed
        if (typeof window !== 'undefined') {
          window.dispatchEvent(new CustomEvent('nod:feed-updated'));
        }

        return {
          success: true,
          id: result.id,
          message: `Article "${title}" published successfully.`,
        };
      }
    },

    // 6. POST COMMENT
    {
      name: 'post_comment',
      description: 'Adds an accessible comment or supportive response to the currently active article.',
      inputSchema: {
        type: 'object',
        properties: {
          articleId: {
            type: 'string',
            description: 'ID of the article being commented on.'
          },
          content: {
            type: 'string',
            description: 'Body text of the comment.'
          }
        },
        required: ['articleId', 'content']
      },
      // Deliberately OMIT readOnlyHint: Mutates community content
      execute: async ({ articleId, content }: { articleId: string; content: string }) => {
        if (!content || content.trim().length < 2) throw new Error('Comment must not be empty.');

        const res = await fetch(`/api/articles/${articleId}/comments`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            content,
            author: { id: 'user-guest', name: 'Kind Reader' },
          }),
        });

        if (!res.ok) throw new Error('Failed to post comment.');
        const store = useStore.getState();
        store.announce('Comment posted successfully.');
        store.setMascotMood('nodding');
        setTimeout(() => store.setMascotMood('idle'), 2000);

        if (typeof window !== 'undefined') {
          window.dispatchEvent(new CustomEvent('nod:comment-added'));
        }

        return { success: true, message: 'Comment posted.' };
      }
    },

    // 7. CONTROL FOCAL READER (Zero-Saccade RSVP with ORP)
    {
      name: 'control_focal_reader',
      description: 'Controls the Zero-Saccade / RSVP focal reader. Use this tool when the user wants to read text one word at a time without moving their eyes, reduce ocular motor strain, eliminate visual clutter for ADHD focus, or adjust reading pace (WPM). Supports start, pause, resume, stop, and speed adjustment.',
      inputSchema: {
        type: 'object',
        properties: {
          action: {
            type: 'string',
            enum: ['start', 'pause', 'resume', 'stop', 'set_speed'],
            description: 'Action to perform on the focal reader: start, pause, resume, stop, or set_speed.'
          },
          wpm: {
            type: 'number',
            description: 'Reading pace in words per minute (e.g., 200, 250, 350). Defaults to current or 250.'
          },
          text: {
            type: 'string',
            description: 'Custom text or prose to read. If omitted during "start", text is extracted from the active article.'
          }
        },
        required: ['action']
      },
      // Deliberately OMIT readOnlyHint: Mutates visible UI / opens overlay
      execute: async ({ action, wpm, text }: { action: 'start' | 'pause' | 'resume' | 'stop' | 'set_speed'; wpm?: number; text?: string }) => {
        const store = useStore.getState();

        if (action === 'start') {
          const targetText = text || store.activeArticle?.content.rawMarkdown || store.activeArticle?.summary || '';
          if (!targetText || targetText.trim().length === 0) {
            throw new Error('Cannot start focal reader: No text provided and no active article is currently open.');
          }
          const targetWpm = wpm && wpm >= 50 ? wpm : 250;
          store.openFocalReader(targetText, targetWpm);
          store.showToast(`✓ Zero-Saccade Reader started (${targetWpm} WPM)`);
          store.setMascotMood('nodding');
          setTimeout(() => store.setMascotMood('idle'), 2000);
          return {
            success: true,
            action: 'start',
            wpm: targetWpm,
            wordCount: useStore.getState().focalReader.words.length,
            message: 'Zero-Saccade focal reader launched and playing.',
          };
        }

        if (action === 'pause') {
          store.pauseFocalReader();
          store.showToast('Zero-Saccade Reader paused');
          return {
            success: true,
            action: 'pause',
            currentIndex: store.focalReader.currentIndex,
            totalWords: store.focalReader.words.length,
            message: 'Zero-Saccade focal reader paused.',
          };
        }

        if (action === 'resume') {
          store.playFocalReader();
          store.showToast('Zero-Saccade Reader resumed');
          return {
            success: true,
            action: 'resume',
            currentIndex: store.focalReader.currentIndex,
            totalWords: store.focalReader.words.length,
            message: 'Zero-Saccade focal reader resumed.',
          };
        }

        if (action === 'stop') {
          store.closeFocalReader();
          store.showToast('Zero-Saccade Reader closed');
          return {
            success: true,
            action: 'stop',
            message: 'Zero-Saccade focal reader closed.',
          };
        }

        if (action === 'set_speed') {
          if (!wpm || wpm < 50 || wpm > 1200) {
            throw new Error('Speed (wpm) is required and must be between 50 and 1200.');
          }
          store.setFocalReaderSpeed(wpm);
          store.showToast(`Pace updated to ${wpm} WPM`);
          return {
            success: true,
            action: 'set_speed',
            wpm,
            message: `Reading speed adjusted to ${wpm} words per minute.`,
          };
        }

        throw new Error(`Unknown action "${action}". Valid actions: start, pause, resume, stop, set_speed.`);
      }
    },

    // 8. GET EDITOR DRAFT (Read into Agent LLM Context)
    {
      name: 'get_editor_draft',
      description: 'Reads the active composer draft (headline, raw content notes, category, tags, and word count) into the agent context window.',
      inputSchema: {
        type: 'object',
        properties: {}
      },
      annotations: {
        readOnlyHint: true,
      },
      execute: async () => {
        const store = useStore.getState();
        const draft = store.editorDraft;
        const wordCount = draft.content ? draft.content.trim().split(/\s+/).filter(Boolean).length : 0;
        return {
          title: draft.title || '',
          content: draft.content || '',
          category: draft.category,
          tags: draft.tags,
          authorName: draft.authorName,
          wordCount,
          hasDraft: Boolean(draft.content && draft.content.trim().length > 0),
        };
      }
    },

    // 9. PROPOSE EDITOR EXPANSION (Binary Gatekeeper Review Trigger)
    {
      name: 'propose_editor_expansion',
      description: 'Injects an expanded, structured article draft directly into the author\'s editor and immediately opens the Zero-Cursor Binary Gatekeeper Review Modal on screen.',
      inputSchema: {
        type: 'object',
        properties: {
          proposal: {
            type: 'string',
            description: 'The expanded, fluent prose or structured article to present to the user for binary keyboard review.'
          },
          title: {
            type: 'string',
            description: 'Suggested title for the article (optional).'
          }
        },
        required: ['proposal']
      },
      // Deliberately OMIT readOnlyHint: Mutates visible UI / opens review modal
      execute: async ({ proposal, title }: { proposal: string; title?: string }) => {
        if (!proposal || proposal.trim().length < 5) {
          throw new Error('Proposal must contain at least 5 characters.');
        }
        const store = useStore.getState();
        store.proposeEditorDraft({ proposedText: proposal, proposedTitle: title });
        return {
          success: true,
          message: 'Proposal injected into editor and Binary Gatekeeper Review Modal displayed on screen.',
        };
      }
    },

    // 10. INSERT PULL QUOTE
    {
      name: 'insert_pull_quote',
      description: 'Inserts an accessible, formatted pull quote with attribution into the active article draft for cognitive emphasis without visual clutter.',
      inputSchema: {
        type: 'object',
        properties: {
          quote: {
            type: 'string',
            description: 'The memorable or emphasized quote statement to highlight.'
          },
          attribution: {
            type: 'string',
            description: 'The speaker, source, or author attribution (optional).'
          }
        },
        required: ['quote']
      },
      // Deliberately OMIT readOnlyHint: Mutates editor text
      execute: async ({ quote, attribution }: { quote: string; attribution?: string }) => {
        if (!quote || quote.trim().length < 3) {
          throw new Error('Quote must contain at least 3 characters.');
        }
        const store = useStore.getState();
        store.insertPullQuote(quote, attribution);
        return {
          success: true,
          message: 'Pull quote formatted and appended to active draft.',
        };
      }
    },

    // 11. PEEK ARTICLE (Zero-Disorientation Modal)
    {
      name: 'peek_article',
      description: 'Opens the centered Zero-Disorientation Quick Peek modal for an article, allowing the user to preview takeaways without losing their place on the feed.',
      inputSchema: {
        type: 'object',
        properties: {
          articleId: {
            type: 'string',
            description: 'The ID of the article to preview (e.g., "seed-001", "seed-002").'
          }
        },
        required: ['articleId']
      },
      // Deliberately OMIT readOnlyHint: Mutates visible DOM / opens modal
      execute: async ({ articleId }: { articleId: string }) => {
        if (!articleId) throw new Error('Article ID is required.');
        const store = useStore.getState();
        store.setPeekArticleId(articleId);
        store.showToast(`✓ Quick Peek opened for article ${articleId}`);
        store.setMascotMood('nodding');
        setTimeout(() => store.setMascotMood('idle'), 2000);
        return {
          success: true,
          articleId,
          message: `Quick Peek preview opened on screen for article ${articleId}.`,
        };
      }
    },

    // 12. CLOSE PEEK
    {
      name: 'close_peek',
      description: 'Closes the active Zero-Disorientation Quick Peek modal or drawer.',
      inputSchema: {
        type: 'object',
        properties: {}
      },
      // Deliberately OMIT readOnlyHint: Mutates visible UI
      execute: async () => {
        const store = useStore.getState();
        store.setPeekArticleId(null);
        return {
          success: true,
          message: 'Quick Peek modal closed.',
        };
      }
    },
  ];
}
